#!/bin/sh
set -eu

expected=$(mktemp)
actual=$(mktemp)

# test 1
input=$(cat <<-'EOF'
col1     col2  col3
hellllo  oh    cool 
col1  col2      col3    
hello cool ess  nice 
EOF
)

cat <<EOF > "$expected"
col1<|>col2<|>col3
hellllo<|>oh<|>cool
col1<|>col2<|>col3
hello<|>cool ess<|>nice
EOF

echo "$input" | fixedwidth2csv -d '<|>' -c 'col1' -c 'col2' -c 'col3' > "$actual"
diff "$actual" "$expected"

#test 2
input=$(cat <<-'EOF'
country       district city
United States New York New York
Canada        Ontario  Toronto

country district      city
France  Île-de-France Paris
Spain   Madrid        Madrid
EOF
)


cat <<EOF > "$expected"
country<|>district<|>city
United States<|>New York<|>New York
Canada<|>Ontario<|>Toronto

country<|>district<|>city
France<|>Île-de-France<|>Paris
Spain<|>Madrid<|>Madrid
EOF

echo "$input" | fixedwidth2csv -d '<|>' -c 'country' -c 'district' -c 'city' > "$actual"
diff "$actual" "$expected"
