#!/bin/sh
set -eu

one_true_awk_version_format='^awk version [[:digit:]][[:digit:]]*$' 

if ! awk --version | grep "$one_true_awk_version_format" > /dev/null ; then
    echo '`awk` on PATH is not the "one true awk". Do you have `gawk` installed as `awk`?' 1>&2
    exit 1
fi

expected=$(mktemp)
actual=$(mktemp)

# test 1
input=$(cat <<-'EOF'
col1     col2  col3
hellllo  oh    cool 
col1  col2      col3    
hello cool ess  nice 
EOF
)

cat <<EOF > "$expected"
col1<|>col2<|>col3
hellllo<|>oh<|>cool
col1<|>col2<|>col3
hello<|>cool ess<|>nice
EOF

echo "$input" | fixedwidth2csv -d '<|>' -c 'col1' -c 'col2' -c 'col3' > "$actual"
diff "$actual" "$expected"

#test 2
input=$(cat <<-'EOF'
country       district city
United States New York New York
Canada        Ontario  Toronto

country district      city
France  Ile-de-France Paris
Spain   Madrid        Madrid
EOF
)

cat <<EOF > "$expected"
country<|>district<|>city
United States<|>New York<|>New York
Canada<|>Ontario<|>Toronto

country<|>district<|>city
France<|>Ile-de-France<|>Paris
Spain<|>Madrid<|>Madrid
EOF

echo "$input" | fixedwidth2csv -d '<|>' -c 'country' -c 'district' -c 'city' > "$actual"
diff "$actual" "$expected"


#test 3
if ! command -v gawk > /dev/null; then
    echo '`gawk` not on PATH. Skipping UTF-8 test.' 1>&2
    exit 0
fi

export PATH=./gawk:$PATH
#generate input and expected with scripts because it difficult to build those precisely without code 

./print_utf8_table_expected > "$expected"
./print_utf8_table_input | fixedwidth2csv -d '<|>' -c 'cats' -c 'city' > "$actual"
diff "$actual" "$expected"
