#!/bin/sh
set -eu

input=$(cat <<-'EOF'
col1     col2  col3
hellllo  oh    cool 
col1  col2      col3
hello coolness  nice 
EOF
)

expected=$(mktemp)
cat <<EOF > "$expected"
col1<|>col2<|>col3
hellllo<|>oh<|>cool 
col1<|>col2<|>col3
hello<|>coolness<|>nice 
EOF

actual=$(mktemp)
echo "$input" | ./fixedwidth2csv -d '<|>' -c 'col1' -c 'col2' -c 'col3' > "$actual"

diff "$actual" "$expected"
