#!/bin/sh
temp=(kmktemp)
(awk 'BEGIN{found = 0}; /exec[[:space:]]+awk/ { found = 1; print; print "\n" } { if (found == 0) { print } }' "$1"; gawk -o- "$(cat "$1" | awk 'BEGIN{found = 0}; /exec[[:space:]]+awk/ { found = 1; next } { if (found == 1) { print } }')") > "$temp"
mv "$temp" "$1"
chmod +x "$1"
